import type { Metadata } from "next";
import { Bakbak_One } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";

const bakbakOne = Bakbak_One({
  variable: "--font-bakbak-one",
  subsets: ["latin"],
  weight: "400"
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bakbakOne.className} antialiased bg-[#040B11]`}
        suppressHydrationWarning
      >
        <Navigation />
          {children}
        <Footer />
      </body>
    </html>
  );
}
